version: '3.5'
volumes:
  data:
  capnp-secrets:
secrets:
  ocurrent-hub:
    external: true
  ocurrent-ssh-key:
    external: true
  ocurrent-tls-key:
    external: true
  ocurrent-slack-endpoint:
    name: "base-builder-slack-endpoint-ci-firehose"
    external: true
  base-builder-oauth:
    external: true
services:
  builder:
    image: base-images
    command: --confirm above-average --confirm-auto-release 120 --slack /run/secrets/ocurrent-slack-endpoint --capnp-address=base-images.ocamllabs.io:8101 --github-oauth /run/secrets/base-builder-oauth
    ports:
      - '8101:9000'
    environment:
      DOCKER_BUILDKIT: 0        # See https://github.com/moby/buildkit/issues/1105
      DEPLOYMENT: 1
    volumes:
      - 'data:/var/lib/ocurrent'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'capnp-secrets:/capnp-secrets'
    secrets:
      - 'base-builder-oauth'
      - 'ocurrent-hub'
      - 'ocurrent-slack-endpoint'
      - source: 'ocurrent-tls-key'
        mode: 0400
      - source: 'ocurrent-ssh-key'
        mode: 0400
