version: '3.1'
volumes:
  data:
secrets:
  ocurrent-hub:
    external: true
  ocurrent-ssh-key:
    external: true
  ocurrent-tls-key:
    external: true
  ocurrent-slack-endpoint:
    external: true
services:
  builder:
    image: base-images
    command: --confirm dangerous --confirm-auto-release 120 --slack /run/secrets/ocurrent-slack-endpoint
    environment:
      DOCKER_BUILDKIT: 0        # See https://github.com/moby/buildkit/issues/1105
    volumes:
      - 'data:/var/lib/ocurrent'
      - '/var/run/docker.sock:/var/run/docker.sock'
    secrets:
      - 'ocurrent-hub'
      - 'ocurrent-slack-endpoint'
      - source: 'ocurrent-tls-key'
        mode: 0400
      - source: 'ocurrent-ssh-key'
        mode: 0400
