version: '3.1'
volumes:
  data:
secrets:
  ocurrent-hub:
    external: true
  ocurrent-ssh-key:
    external: true
services:
  builder:
    image: base-images
    command: --confirm dangerous
    environment:
      DOCKER_BUILDKIT: 0        # See https://github.com/moby/buildkit/issues/1105
    ports:
     - "8080:8080"
    volumes:
      - 'data:/var/lib/ocurrent'
      - '/var/run/docker.sock:/var/run/docker.sock'
    secrets:
      - 'ocurrent-hub'
      - source: 'ocurrent-ssh-key'
        mode: 0400
